# .github/workflows/release-helm-chart.yml

name: Release Helm Chart

on:
  push:
    branches:
      - main
      - devel
    # Only run this workflow if files in the helm-chart directory change.
    paths:
      - 'helm-chart/**'

# Ensures that only one workflow runs at a time for the same branch,
# cancelling any in-progress runs when a new one is triggered.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Helm Lint
        run: helm lint ./helm-chart

  release:
    needs: lint # This job will only run if the 'lint' job succeeds.
    # Grant permissions to create a GitHub Release and push to the gh-pages branch.
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetches all history for all branches and tags, which is required
          # by the chart-releaser action to determine changes.
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1 # Use the latest v1.x.y release
        with:
          charts_dir: helm-chart
          # The path to the chart directory.
          # If the push is to the 'devel' branch, mark the GitHub Release as a pre-release.
          # Otherwise, it will be a full release.
          prerelease: ${{ github.ref == 'refs/heads/devel' }}
        env:
          # The chart-releaser action uses this token to create releases and push to gh-pages.
          # GITHUB_TOKEN is automatically provided by GitHub Actions.
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
